name: Python application

on:
  schedule:
    # 13:50 Greek time (UTC+3) on Tuesday 29/07/2025 is 10:50 UTC
    - cron: '50 10 29 7 2'
    - cron: '51 10 29 7 2' # Minute 51, Hour 10 (UTC), Day 29, Month 7 (July), Day of Week 2 (Tuesday)
  workflow_dispatch: # Allows manual triggering

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright browsers
      run: |
        python -m playwright install

    - name: Run b.py
      env:
        PIS_USERNAME: ${{ secrets.PIS_USERNAME }}
        PIS_PASSWORD: ${{ secrets.PIS_PASSWORD }}
      run: |
        python test_bot.py

    - name: Upload HTML artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pis-gr-scraper-html-test
        path: |
          *.html
          application_assets/*
        if-no-files-found: warn

    - name: Send artifacts via email
      env:
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      run: |
        python send_artifact_email.py
