name: Python application

on:
  schedule:
    # 13:55 Greek time (UTC+3) on Tuesday 29/07/2025 is 10:55 UTC
    - cron: '55 10 29 7 2'
    - cron: '56 10 29 7 2' # Minute 56, Hour 10 (UTC), Day 29, Month 7 (July), Day of Week 2 (Tuesday)
  workflow_dispatch: # Allows manual triggering

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright browsers
      run: |
        python -m playwright install

    - name: Run bot.py
      env:
        PIS_USERNAME: ${{ secrets.PIS_USERNAME }}
        PIS_PASSWORD: ${{ secrets.PIS_PASSWORD }}
      run: |
        python bot.py

    - name: Upload HTML artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pis-gr-scraper-html
        path: |
          application_view_*.html
          login_failed_response.html
        if-no-files-found: warn
