name: Python application test run

on:
  schedule:
    # Test it 21:55 Greek time (UTC+3) on Monday 28/07/2025 is 18:55 UTC
    - cron: '50 18 28 7 1'
    - cron: '51 18 28 7 1' # Minute 51, Hour 18 (UTC), Day 28, Month 7 (July), Day of Week 1 (Monday)
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright browsers
      run: |
        python -m playwright install

    - name: Run b.py
      env:
        PIS_USERNAME: ${{ secrets.PIS_USERNAME }}
        PIS_PASSWORD: ${{ secrets.PIS_PASSWORD }}
      run: |
        python test_bot.py

    - name: Upload HTML artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pis-gr-scraper-html-test
        path: |
          *.html
          application_assets/*
        if-no-files-found: warn

    - name: Send artifacts via email
      env:
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        SMTP_RECEIVER: ${{ secrets.SMTP_USERNAME }}
      run: |
        python send_artifact_email.py
